[package]
name = "trash"
version = "0.1.1"
authors = ["Michael Zhang <iptq@protonmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
env_logger = "0.6"
lazy_static = "1.0"
log = "0.4"
regex = "1.1"
structopt = "0.2"
walkdir = "2.2"
xdg = "2.2"
